# Generated by Django 4.0.4 on 2022-05-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='Alias')),
                ('long_url', models.URLField(max_length=500, verbose_name='Long URL')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'Most viewed links',
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='users.shorturl')),
            ],
        ),
    ]
