# Generated by Django 4.0.4 on 2022-05-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shorturl_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.DeleteModel(
            name='ShortUrl',
        ),
    ]
