# Generated by Django 4.0.4 on 2022-05-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_analytics_delete_shorturl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
