# Generated by Django 4.0.4 on 2022-05-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='user',
        ),
    ]
