# Generated by Django 4.0.4 on 2022-05-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_urlmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='user',
        ),
    ]
