# Generated by Django 4.0.4 on 2022-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500)),
                ('short_url', models.CharField(max_length=32, unique=True)),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Most viewed links',
            },
        ),
    ]
