# Generated by Django 4.0.4 on 2022-05-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_authmodel_analytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.DeleteModel(
            name='AuthModel',
        ),
    ]
